version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package flyway:migrate -Dflyway.url=jdbc:postgresql://$RDS_HOSTNAME:$RDS_PORT/$RDS_DB_NAME -Dflyway.user=$RDS_USERNAME -Dflyway.password=$RDS_PASSWORD -Dflyway.locations=filesystem:db/migration -e
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/api.jar
  discard-paths: yes